version: "3"

networks:
  web:
    external: true

services:
  kaistore-bot:
    image: $DOCKER_IMAGE
    environment:
      APP_NAME: $APP_NAME
      LOGGER_ENABLED: $LOGGER_ENABLED
      LOGGER_LEVEL: $LOGGER_LEVEL
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_DATABASE: $DB_DATABASE
      DB_ENABLE_SSL: $DB_ENABLE_SSL
    labels:
      - traefik.http.routers.kaistore-bot.rule=Host(`${TRAEFIK_HOST}`)
      - traefik.http.routers.kaistore-bot.tls=true
      - traefik.http.routers.kaistore-bot.tls.certresolver=lets-encrypt
      - traefik.port=80
      - traefik.http.services.kaistore-bot.loadbalancer.server.port=${SERVER_PORT}
    networks:
      - web